### ISSUE TITLE
[Feature] Update CI/GitHub Action in GenericBucket

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/BucketTemplate#1]
## Feature Request
Sorry if this is not the right place to ask, I can't open issue in GenericBucket.

#### Is your feature request related to a problem? Please describe.

GenericBucket doesn't have the same feature as known bucket because it's using old yml file and old repo for GitHub Action, is this intentional or you guys forgot to update it?

#### Describe the solution you'd like

Use .github folder from known bucket for GenericBucket and also add `appveyor.yml`(?)

#### I also have some question:
- Does the autoupdate thingy comitted by github-action bot is what you guys called Excavator?
- Does it run purely on github action (dont need to set up anything outside github)?

**Comment by LazyGeniusMan** [comment]
So all files is updated ? just need to complete the readme?

If I click `Use This Template` right now, can I fetch the commits made after that? I'm not sure what's the difference between that and forking.

**Comment by rashil2000** [comment]
> So all files are updated ? just need to complete the readme?

Readme is also complete. Anything missing?

> If I click `Use This Template` right now, can I fetch the commits made after that? I'm not sure what's the difference between that and forking.

No, see here https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template. You will have to add the subsequent commits manually.

**Comment by LazyGeniusMan** [comment]
> Anything missing?

Looks like it;s complete, sorry, I;m under impresion it's not complete because it's so short compare to the old one.

uhh I think there is a problem, my bucket excavator is error. look at this : https://github.com/LazyGeniusMan/Scoop-Genshin/runs/4647308116?check_suite_focus=true#step:3:174

it's trying to pull `master` branch, but this template and their children have `main` branch.

Compare to successful excavator : https://github.com/ScoopInstaller/Extras/runs/4647239885?check_suite_focus=true#step:3:182

**Comment by rashil2000** [comment]
I don't have admin access to the repo. @issaclin32 can you rename the default branch to `master` instead of `main`?

**Comment by LazyGeniusMan** [comment]
Can confirm that it's worked after I rename the branch to `master`

https://github.com/LazyGeniusMan/Scoop-Genshin/runs/4648104752?check_suite_focus=true#step:3:188

**Comment by LazyGeniusMan** [comment]
I have a suggestion. What if the excavator is also allowed to run if someone comment specific thing on a specific issue?, something similiar to "/verify" for PR, but this is for issue (the issue can be pinned with title like :"App outdated? update here".

I was thinking maybe there is someone who's like "The official release is out, I want to update it in scoop right now" kind of thing lol

Is that dumb? haha

**Comment by rashil2000** [comment]
> I was thinking maybe there is someone who's like "The official release is out, I want to update it in scoop right now" kind of thing lol

For such things, we usually tell them to wait for a couple hours or so.

For other generic issue types, like hash fails, decompress errors, 404 errors, they are already handled by their respective titles.

Still, if you have other ideas, we can discuss it in an issue in GitHubActions repo

**Comment by LazyGeniusMan** [comment]
> we can discuss it in an issue in GitHubActions repo

Ah yea that suggestion is under Github Action repo scope. Looks like the GitHub Actionis handle by trigger event type (`on<event_name>`)? at first I thought it's handle by Job ID, Job Name, Step ID, or Step name so I can just change the `.yml` workflow file

**Comment by rashil2000** [comment]
You can set when to trigger the action using the yml file, and the logic for handling that is here - https://github.com/ScoopInstaller/GithubActions/blob/main/src/ActionWrapper.psm1

**Comment by LazyGeniusMan** [comment]
Yea, that's why I said I also need to edit the GitHubAction script If I want to implement my thing above (force run excavator similiar to /verify), because if I wrote Workflow 
```
on: 
    issue_comment
...
      if: contains(github.event.comment.html_url, '/issue/')
      if: contains(github.event.comment.body, '/update)
```
it wont trigger the excavator script, instead it will trigger the PR script.

Unless I misunderstand the script ?

**Comment by rashil2000** [comment]
Yes, correct

**Comment by issaclin32** [comment]
> I don't have admin access to the repo. @issaclin32 can you rename the default branch to `master` instead of `main`?

Done.
