### ISSUE TITLE
[Bug]: Test workflow Could not find a project

### ISSUE THREAD

**Issue by Jvcon** [ScoopInstaller/BucketTemplate#11]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

N/A

### Expected/Current Behaviour

This template actions

### Steps to Reproduce

```console
https://github.com/Jvcon/werkzeuge/actions/runs/5816070288
```

### Possible Solution

N/A

### Scoop and Buckets Version

```console
N/A
```

### Scoop Config

```console
N/A
```

### PowerShell Version

```console
N/A
```

**Comment by rashil2000** [comment]
Could you try re-running the action? Or do a fresh run.
