### ISSUE TITLE
How to make my bucket not indexed by scoop search engine? 

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/BucketTemplate#3]
Hi, I want to make a testing bucket, how do I make them not detected by scoop search engine like [ScoopSearch](https://scoopsearch.github.io/#/apps) and [scoop-directory](https://rasa.github.io/scoop-directory) ?

**Comment by rashil2000** [comment]
If I remember correctly, scoop-directory scrapes the GitHub Search API and picks up repositories with 'scoop' in their name or their topics. I assume ScoopSearch also uses something similar. Still I think it will be best if you ask the respective authors in their repositories. 

So you can name the repository accordingly and set its topics accordingly to avoid it getting indexed.

**Comment by rasa** [comment]
Sccop Directory [searches](https://github.com/rasa/scoop-directory/blob/b84caa7ef02782b0a8db6abd45ef17081b6fbe7a/maintenance/github-crawler.py#L1027) for 
```
    "topic:scoop-bucket",
    "scoop-bucket",
    "scoop bucket",
    "scoop",
```
ScoopSearch searches
```
    "topic:scoop-bucket",
    "scoop-bucket",
    "scoop bucket"
```
per [here](https://github.com/ScoopSearch/ScoopSearch.AzureFunctions/blob/663bfe4103504a87c9a5fc9a1a566381c881404b/src/ScoopSearch.Functions/settings.json#L5):
```
            "https://api.github.com/search/repositories?q=topic:scoop-bucket",
            // Split search queries as GitHub search API returns at most 1000 results
            "https://api.github.com/search/repositories?q=scoop-bucket+created%3A%3E%3D2020-01-01",
            "https://api.github.com/search/repositories?q=scoop-bucket+created%3A%3C2020-01-01",
            "https://api.github.com/search/repositories?q=scoop+bucket+created%3A%3E%3D2020-01-01",
            "https://api.github.com/search/repositories?q=scoop+bucket+created%3A%3C2020-01-01"
```

**Comment by LazyGeniusMan** [comment]
Ok thanks for the answer, looks like not mentioning "scoop" in bucket name and description and delete all readme file is working.
